{{- if .Values.kube-prometheus-stack.alertmanager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-alertmanager-config
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alertmanager@example.com'
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          severity: P1
        receiver: 'critical-alerts'
      - match:
          severity: P2
        receiver: 'warning-alerts'
    
    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://127.0.0.1:5001/'
    
    - name: 'critical-alerts'
      webhook_configs:
      - url: 'http://127.0.0.1:5001/critical'
    
    - name: 'warning-alerts'
      webhook_configs:
      - url: 'http://127.0.0.1:5001/warning'
{{- end }}