{{- if .Values.nodeExporter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-node-exporter
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "venus-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        {{- include "venus-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: node-exporter
    spec:
      {{- include "venus-monitoring.imagePullSecrets" . | nindent 6 }}
      hostNetwork: true
      hostPID: true
      containers:
        - name: node-exporter
          image: "{{ include "venus-monitoring.image" .Values.nodeExporter.image }}"
          imagePullPolicy: {{ .Values.nodeExporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          args:
            - --path.rootfs=/host
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($|/)
            - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /host
              readOnly: true
          resources:
            {{- toYaml .Values.nodeExporter.resources | nindent 12 }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
      tolerations:
        - effect: NoSchedule
          operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-node-exporter
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nodeExporter.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.service.port }}
      targetPort: 9100
  selector:
    {{- include "venus-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
{{- end }}