{{- if .Values.prometheusRules.gpu.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-gpu-rules
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  groups:
    - name: gpu-alerts
      rules:
        # GPU 温度过高
        - alert: GPUTemperatureHigh
          expr: DCGM_FI_DEV_GPU_TEMP > 85
          for: 5m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0101"
          annotations:
            summary: "GPU 温度过高"
            description: "GPU {{ $labels.gpu }} 温度过高: {{ $value }}°C"
            ip: "{{ $labels.instance }}"
        
        # GPU 功耗过高
        - alert: GPUPowerHigh
          expr: DCGM_FI_DEV_POWER_USAGE > 300
          for: 5m
          labels:
            severity: P2
            alert_type: "HARD_WARE"
            id: "GPU_0102"
          annotations:
            summary: "GPU 功耗过高"
            description: "GPU {{ $labels.gpu }} 功耗过高: {{ $value }}W"
            ip: "{{ $labels.instance }}"
        
        # GPU ECC 错误
        - alert: GPUECCError
          expr: DCGM_FI_DEV_ECC_DBE_VOL_TOTAL > 0
          for: 1m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0103"
          annotations:
            summary: "GPU ECC 错误"
            description: "GPU {{ $labels.gpu }} 检测到 ECC 错误: {{ $value }}"
            ip: "{{ $labels.instance }}"
        
        # GPU 掉卡
        - alert: GPUDown
          expr: up{job="nvidia-gpu-exporter"} == 0
          for: 1m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0104"
          annotations:
            summary: "GPU 掉卡"
            description: "GPU {{ $labels.instance }} 掉卡"
            ip: "{{ $labels.instance }}"
{{- end }}

---
{{- if .Values.prometheusRules.node.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-node-rules
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  groups:
    - name: node-alerts
      rules:
        # 节点 CPU 使用率过高
        - alert: NodeCPUHigh
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: P2
            alert_type: "SOFT_WARE"
            id: "NODE_0101"
          annotations:
            summary: "节点 CPU 使用率过高"
            description: "节点 {{ $labels.instance }} CPU 使用率过高: {{ $value }}%"
            ip: "{{ $labels.instance }}"
        
        # 节点内存使用率过高
        - alert: NodeMemoryHigh
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
          for: 5m
          labels:
            severity: P2
            alert_type: "SOFT_WARE"
            id: "NODE_0102"
          annotations:
            summary: "节点内存使用率过高"
            description: "节点 {{ $labels.instance }} 内存使用率过高: {{ $value }}%"
            ip: "{{ $labels.instance }}"
        
        # 节点磁盘使用率过高
        - alert: NodeDiskHigh
          expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
          for: 5m
          labels:
            severity: P2
            alert_type: "SOFT_WARE"
            id: "NODE_0103"
          annotations:
            summary: "节点磁盘使用率过高"
            description: "节点 {{ $labels.instance }} 磁盘使用率过高: {{ $value }}%"
            ip: "{{ $labels.instance }}"
        
        # 节点网络错误率过高
        - alert: NodeNetworkErrorHigh
          expr: rate(node_network_receive_errs_total[5m]) + rate(node_network_transmit_errs_total[5m]) > 0.1
          for: 5m
          labels:
            severity: P2
            alert_type: "SOFT_WARE"
            id: "NODE_0104"
          annotations:
            summary: "节点网络错误率过高"
            description: "节点 {{ $labels.instance }} 网络错误率过高: {{ $value }}"
            ip: "{{ $labels.instance }}"
{{- end }}

---
{{- if .Values.prometheusRules.k8s.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-k8s-rules
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  groups:
    - name: k8s-alerts
      rules:
        # Pod 重启次数过多
        - alert: PodRestartHigh
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0.1
          for: 5m
          labels:
            severity: P2
            alert_type: "SOFT_WARE"
            id: "K8S_0101"
          annotations:
            summary: "Pod 重启次数过多"
            description: "Pod {{ $labels.pod }} 重启次数过多: {{ $value }}"
            ip: "{{ $labels.instance }}"
        
        # Pod 状态异常
        - alert: PodStatusAbnormal
          expr: kube_pod_status_phase{phase!="Running",phase!="Succeeded"} > 0
          for: 5m
          labels:
            severity: P2
            alert_type: "SOFT_WARE"
            id: "K8S_0102"
          annotations:
            summary: "Pod 状态异常"
            description: "Pod {{ $labels.pod }} 状态异常: {{ $labels.phase }}"
            ip: "{{ $labels.instance }}"
        
        # 节点状态异常
        - alert: NodeStatusAbnormal
          expr: kube_node_status_condition{condition="Ready",status="false"} > 0
          for: 5m
          labels:
            severity: P1
            alert_type: "SOFT_WARE"
            id: "K8S_0103"
          annotations:
            summary: "节点状态异常"
            description: "节点 {{ $labels.node }} 状态异常: {{ $labels.condition }}"
            ip: "{{ $labels.instance }}"
{{- end }}

---
{{- if .Values.prometheusRules.ipmi.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-ipmi-rules
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  groups:
    - name: ipmi-alerts
      rules:
        # IPMI 传感器状态异常
        - alert: IPMISensorStatus
          expr: ipmi_sensor_state != 1
          for: 30s
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "IPMI_0101"
          annotations:
            summary: "IPMI 传感器状态异常"
            description: "节点 {{ $labels.instance }} 传感器 {{ $labels.sensor_name }} 状态异常: {{ $labels.sensor_state }}"
            ip: "{{ $labels.instance }}"
        
        # IPMI 温度过高
        - alert: IPMITemperatureHigh
          expr: ipmi_sensor_temperature_celsius > 75
          for: 5m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "IPMI_0102"
          annotations:
            summary: "IPMI 温度过高"
            description: "节点 {{ $labels.instance }} 温度过高: {{ $value }}°C"
            ip: "{{ $labels.instance }}"
        
        # IPMI 风扇故障
        - alert: IPMIFanFailure
          expr: ipmi_sensor_fan_speed_rpm == 0
          for: 1m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "IPMI_0103"
          annotations:
            summary: "IPMI 风扇故障"
            description: "节点 {{ $labels.instance }} 风扇 {{ $labels.sensor_name }} 故障"
            ip: "{{ $labels.instance }}"
        
        # IPMI 电源故障
        - alert: IPMIPowerFailure
          expr: ipmi_sensor_power_state != 1
          for: 1m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "IPMI_0104"
          annotations:
            summary: "IPMI 电源故障"
            description: "节点 {{ $labels.instance }} 电源状态异常: {{ $labels.sensor_state }}"
            ip: "{{ $labels.instance }}"
        
        # IPMI 电压异常
        - alert: IPMIVoltageAbnormal
          expr: ipmi_sensor_voltage_volts < 11.5 or ipmi_sensor_voltage_volts > 12.5
          for: 5m
          labels:
            severity: P2
            alert_type: "HARD_WARE"
            id: "IPMI_0105"
          annotations:
            summary: "IPMI 电压异常"
            description: "节点 {{ $labels.instance }} 电压异常: {{ $value }}V"
            ip: "{{ $labels.instance }}"
        
        # IPMI 内存 ECC 错误
        - alert: IPMIMemoryError
          expr: ipmi_sensor_memory_ecc_errors > 0
          for: 1m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "IPMI_0106"
          annotations:
            summary: "IPMI 内存 ECC 错误"
            description: "节点 {{ $labels.instance }} 内存 ECC 错误: {{ $value }}"
            ip: "{{ $labels.instance }}"
        
        # IPMI 磁盘故障
        - alert: IPMIDiskFailure
          expr: ipmi_sensor_disk_state != 1
          for: 1m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "IPMI_0107"
          annotations:
            summary: "IPMI 磁盘故障"
            description: "节点 {{ $labels.instance }} 磁盘 {{ $labels.sensor_name }} 故障"
            ip: "{{ $labels.instance }}"
        
        # IPMI 网络接口故障
        - alert: IPMINetworkInterfaceFailure
          expr: ipmi_sensor_network_interface_state != 1
          for: 1m
          labels:
            severity: P2
            alert_type: "HARD_WARE"
            id: "IPMI_0108"
          annotations:
            summary: "IPMI 网络接口故障"
            description: "节点 {{ $labels.instance }} 网络接口 {{ $labels.sensor_name }} 故障"
            ip: "{{ $labels.instance }}"
        
        # IPMI BMC 不可达
        - alert: IPMIBMCDown
          expr: up{job="ipmi-exporter"} == 0
          for: 1m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "IPMI_0109"
          annotations:
            summary: "IPMI BMC 不可达"
            description: "节点 {{ $labels.instance }} BMC 不可达"
            ip: "{{ $labels.instance }}"
{{- end }}