{{- if .Values.serviceMonitors.nodeExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-node-exporter
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "venus-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node-exporter
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}

---
{{- if .Values.serviceMonitors.kubeStateMetrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-kube-state-metrics
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "venus-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kube-state-metrics
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}

---
{{- if .Values.serviceMonitors.nvidiaGpuExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-nvidia-gpu-exporter
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "venus-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nvidia-gpu-exporter
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}

---
{{- if .Values.serviceMonitors.harborExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-harbor-exporter
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "venus-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: harbor-exporter
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}

---
{{- if .Values.serviceMonitors.postgresExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-postgres-exporter
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "venus-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres-exporter
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}

---
{{- if .Values.serviceMonitors.volcanoScheduler.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-volcano-scheduler
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "venus-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: volcano-scheduler
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}

---
{{- if .Values.serviceMonitors.ipmiExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "venus-monitoring.fullname" . }}-ipmi-exporter
  namespace: {{ include "venus-monitoring.namespace" . }}
  labels:
    {{- include "venus-monitoring.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "venus-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ipmi-exporter
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}