name: Notify New Issue to Feishu

on:
  issues:
    types: [opened,edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Feishu
        run: |
          curl -X POST ${{ secrets.FEISHU_WEBHOOK_URL }} \
          -H 'Content-Type: application/json' \
          -d '{
                "msg_type": "text",
                "content": {
                  "text": "🔔 New GitHub Issue: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})"
                }
              }'
